git:
    submodules: false
language: cpp
before_install:
    - build/travis/presetup ${TRAVIS_OS_NAME}
install:
    - build/travis/setup ${TRAVIS_OS_NAME}
    - mkdir -p /tmp/include/ThorSerialize
    - curl https://raw.githubusercontent.com/Loki-Astari/ThorsSerializer/master/src/Serialize/Traits.h > /tmp/include/ThorSerialize/Traits.h
script:
    - "./configure --with-boost=/tmp/extra --disable-binary"
    - export PATH=${PATH}:export CXXFLAGS=-I/tmp/include/;$(pwd)/build/bin;make
after_success:
    - "./CreateHeaderOnly"
    - bash <(curl -s https://codecov.io/bash)
branches:
    only:
        - master
        - "/^Feature-.*$/"
env:
    global:
    - secure: D5HPaNoM+cbZLcfqGvudY3irPd27q89npzr7jlaVjs1m782bii8XCKWwrwNQfge/7mtaY7RRDxdFJkRssVno5HaLItOg/MT6gBinyQGenPZXeh7ia2CYkeuiRhKrEfKAMhCcoe5RafYbCDWq8w5eZ6iMnRoFUiA66cWGlF1vBI4=
