#!/bin/bash -v

for loop in src/Serialize/*.cpp; do
    file=${loop##*/}
    base=${file%%.cpp}
    echo cp ${file} build/include/ThorSerialize/${base}.source
    cp ${loop} build/include/ThorSerialize/${base}.source
done

git clone --single-branch --branch header-only https://Loki-Astari:${TMP}@github.com/Loki-Astari/ThorsStorage.git /tmp/TS

rm /tmp/TS/ThorsStorage/*
cp build/include/ThorsStorage/*  /tmp/TS/ThorsStorage/
cd /tmp/TS
git checkout ThorsStorage/ThorsStorageConfig.h

git add ThorsStorage/*
git commit -m "Update the header only build to latest version"
git push

